# Generated by Django 4.0.6 on 2023-02-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairhireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
