# Generated by Django 4.0.6 on 2023-02-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairhireapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
