# Generated by Django 4.0.6 on 2023-02-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairhireapp', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Logged',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
